### ISSUE TITLE
2D code - varying size of the blocks

### ISSUE THREAD

**Issue by ismajli** [EszopiCoder/excel-barcode-fx-library#4]
Dear developer team,
I tried this library on a Windows 10 Enterprice system with Microsoft 365 Excel.
It seems that the 2D codes have some issues, because the size of the generated blocks are incorrect.
Some of the black sqares have the right size, but some are like half the needed width or height.
Even if I just re-generate the example codes, they generate strangely.
I attached a screenshot of the result. The first line is original, the second line I re-generated.

![Issue_Example](https://github.com/EszopiCoder/excel-barcode-fx-library/assets/31255948/e8a426d1-2077-41a0-a1a0-f2ca4d94b6a5)

Thank you in advance for your great work!
Br

**Comment by EszopiCoder** [comment]
Hi!

Thank you for your email. I just opened this on Windows 10 home edition
with Microsoft 365 Excel too. The barcode sizing was off since I last
opened the file months ago. I used the update barcode function to
re-generate the barcodes and automatically resize them to the size of the
cell. I can’t seem to generate the error you mentioned. What are the exact
steps you are taking to generate this error?

I should also mentioned that I didn’t write most of the code for the 2D
barcodes. I borrowed it from others and credited them in my README.

**Comment by ismajli** [comment]
Hi!
Thanks a lot for your very fast and helpful reply.

I tried to re-generate the error today but now it seems to work.
I am very sorry but I really can't tell you the reason of the buggy generation.

I also compared your code with the original one and I couldn't find any deviations.

I will use this code more frequently in the following days and I will let you know when I find something out.

Thanks a lot again and best regards.

**Comment by ismajli** [comment]
Hi!
now I am able to reproduce the bug.
It depends on the display(resolution) I am using especially with

**Comment by ismajli** [comment]
Hello again,
now I know how to re-generate the bug.
When I connect my notebook to an external display and I generate the 2D image, while the excel sheet is opened on the external display, than the code gets generated buggy.
When I move the excel-application to my notebook-display (still connected to the external display), and I re-generate the 2D codes, then there is no bug.

So I assume the code consider for some calculations always the resolution of the native notebook screen and for other calculations the currently shown display, so that there is an inconsistency in the generated 2D image.

I checked the VBA code but I am no expert in this area, so I was not able to find the bug.

Thank you and best regards.
